version: '3.6'

services:

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./nginx
    volumes:
      - "./var/www/html:/var/www/html"

  wordpress:
    depends_on:
      - mysql
    build:
      context: ./wordpress
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'UPLOADS', 'wp-content/uploads' );
    volumes:
      - "./var/www/html:/var/www/html"

  mysql:
    build:
      context: ./mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./var/mysql:/var/lib/mysql"
